//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UVEngine.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UVEngine {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UVEngine() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UVEngine.Resources.UVEngine", typeof(UVEngine).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Continue 的本地化字符串。
        /// </summary>
        public static string _continue {
            get {
                return ResourceManager.GetString("_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This feature is only provided for removing some files which you don&apos;t need any more, such as &quot;temp.zip&quot;. Removing other files may cause your data damage. 的本地化字符串。
        /// </summary>
        public static string aboutfileclear {
            get {
                return ResourceManager.GetString("aboutfileclear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UVE Game Engine is an application designed by Light Studio
        ///Currently we are working on:
        ///ONScripter Compatible Layer (Completed)
        ///ONScripter-jh Compatible Layer (Completed, Current Version)
        ///UVE Next Native Language (Planning)
        ///Kirikiri Compatible Layer (Planning)
        ///Most of the ONScripter/NScripter games can run on UVE now. For more information, please visit:
        ///Open source tools: http://uve.codeplex.com/
        ///Email: uve@ligstd.com
        ///Blog: http://uve-project.ml (Simplified Chinese)
        ///warining: This software (UVE, U [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string aboutInfo {
            get {
                return ResourceManager.GetString("aboutInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About us 的本地化字符串。
        /// </summary>
        public static string aboutus {
            get {
                return ResourceManager.GetString("aboutus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Before using this service, please confirm that your age is more than 13. 的本地化字符串。
        /// </summary>
        public static string agecomfirm {
            get {
                return ResourceManager.GetString("agecomfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Analyzing the file 的本地化字符串。
        /// </summary>
        public static string analyzing {
            get {
                return ResourceManager.GetString("analyzing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Config File 的本地化字符串。
        /// </summary>
        public static string appconfig {
            get {
                return ResourceManager.GetString("appconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UVE Game Center 的本地化字符串。
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UVE Settings 的本地化字符串。
        /// </summary>
        public static string appsettings {
            get {
                return ResourceManager.GetString("appsettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 It seems to be your first time to run the application. Do you want to have a performance test for your phone? 的本地化字符串。
        /// </summary>
        public static string askbenchmark {
            get {
                return ResourceManager.GetString("askbenchmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Available RAM for this app : 的本地化字符串。
        /// </summary>
        public static string availableram {
            get {
                return ResourceManager.GetString("availableram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back 的本地化字符串。
        /// </summary>
        public static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save data backup 的本地化字符串。
        /// </summary>
        public static string backup {
            get {
                return ResourceManager.GetString("backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backup completed! 的本地化字符串。
        /// </summary>
        public static string backupcomplete {
            get {
                return ResourceManager.GetString("backupcomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The remain file of your last benchmark 的本地化字符串。
        /// </summary>
        public static string benchremain {
            get {
                return ResourceManager.GetString("benchremain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Our Developer Blog(CHS)
        ///http://uve-project.ml 的本地化字符串。
        /// </summary>
        public static string blog {
            get {
                return ResourceManager.GetString("blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Buy Donate version in store($1.99) 的本地化字符串。
        /// </summary>
        public static string buyinstore {
            get {
                return ResourceManager.GetString("buyinstore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cache file 的本地化字符串。
        /// </summary>
        public static string cache {
            get {
                return ResourceManager.GetString("cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change background picture 的本地化字符串。
        /// </summary>
        public static string changeBackground {
            get {
                return ResourceManager.GetString("changeBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete all files in UVE 的本地化字符串。
        /// </summary>
        public static string clearall {
            get {
                return ResourceManager.GetString("clearall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 restore settings to default 的本地化字符串。
        /// </summary>
        public static string clearallsettings {
            get {
                return ResourceManager.GetString("clearallsettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure to remove all files? 的本地化字符串。
        /// </summary>
        public static string clearconfirm {
            get {
                return ResourceManager.GetString("clearconfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This operation will remove the following items permanly :
        ///1.All of the UVE games imported to phone.
        ///2.All of the save data of UVE games.
        ///3.The settings of this app.
        ///4.OpenXLive login session.
        ///5.Your background image.
        ///6.All the cache of this app.
        ///
        ///It will not remove :
        ///1.Games in SD card.
        ///2.Skydrive backups.
        ///3.OpenXLive online personal information.
        ///4.This app itself.
        ///
        ///Are you sure to remove all? 的本地化字符串。
        /// </summary>
        public static string clearwarning {
            get {
                return ResourceManager.GetString("clearwarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cloud backup 的本地化字符串。
        /// </summary>
        public static string cloudbackup {
            get {
                return ResourceManager.GetString("cloudbackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please sign in and authorize the app to access your SkyDrive first.
        ///&quot;Backup&quot; operation will pack up all the existed saves first and upload them to your SkyDrive and wipe all the backup data in the cloud.
        ///&quot;Recover&quot; operation will download your cloud backup from SkyDrive and recover them. Files will be overwritten if existed in the local storage. 的本地化字符串。
        /// </summary>
        public static string clouddesc {
            get {
                return ResourceManager.GetString("clouddesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ONS/NS Convert Tool(CHS and English)
        ///http://uve.codeplex.com 的本地化字符串。
        /// </summary>
        public static string codeplex {
            get {
                return ResourceManager.GetString("codeplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you really want to delete the game? 的本地化字符串。
        /// </summary>
        public static string comfirmdelete {
            get {
                return ResourceManager.GetString("comfirmdelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm 的本地化字符串。
        /// </summary>
        public static string comfirminfo {
            get {
                return ResourceManager.GetString("comfirminfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compression error : 的本地化字符串。
        /// </summary>
        public static string compressionerror {
            get {
                return ResourceManager.GetString("compressionerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm 的本地化字符串。
        /// </summary>
        public static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm again 的本地化字符串。
        /// </summary>
        public static string confirmagain {
            get {
                return ResourceManager.GetString("confirmagain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure to remove this folder/file? 的本地化字符串。
        /// </summary>
        public static string confirmdelete {
            get {
                return ResourceManager.GetString("confirmdelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RAM usage 的本地化字符串。
        /// </summary>
        public static string currentram {
            get {
                return ResourceManager.GetString("currentram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Currently using : 的本地化字符串。
        /// </summary>
        public static string currentusingram {
            get {
                return ResourceManager.GetString("currentusingram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current : 的本地化字符串。
        /// </summary>
        public static string currprog {
            get {
                return ResourceManager.GetString("currprog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 delete 的本地化字符串。
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The game is being removed. It may be not  completedly removed if you exit now. Do you still want to exit? 的本地化字符串。
        /// </summary>
        public static string deleting {
            get {
                return ResourceManager.GetString("deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If you have any problems, Please click &quot;About&quot; . 的本地化字符串。
        /// </summary>
        public static string detailedInfo {
            get {
                return ResourceManager.GetString("detailedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Following Directories has been detected 的本地化字符串。
        /// </summary>
        public static string detectedfolders {
            get {
                return ResourceManager.GetString("detectedfolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disk 的本地化字符串。
        /// </summary>
        public static string disk {
            get {
                return ResourceManager.GetString("disk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disk performance score: 的本地化字符串。
        /// </summary>
        public static string diskscore {
            get {
                return ResourceManager.GetString("diskscore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backup 的本地化字符串。
        /// </summary>
        public static string dobackup {
            get {
                return ResourceManager.GetString("dobackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Donate 的本地化字符串。
        /// </summary>
        public static string donate {
            get {
                return ResourceManager.GetString("donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 We&apos;ve spent a lot of money on the following test devices and services:\nMicrosoft App Hub\nLumia 920\nLumia 820\nLumia 520\nHTC 8s\nSamsung ATIV S\nBut we still published a full free version because we wish everyone who uses WP8 can enjoy this software for free as Android or iOs users do. We would be really happy if you are willing to donate to us so that we can do better and keep updating the software for free. Use the &quot;Donate&quot; button to get more specific information, or continue if you don&apos;t want to donat [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string donatedesc {
            get {
                return ResourceManager.GetString("donatedesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Donate now 的本地化字符串。
        /// </summary>
        public static string donatedirectly {
            get {
                return ResourceManager.GetString("donatedirectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There are two ways to donate to us 的本地化字符串。
        /// </summary>
        public static string donatemethoddesc {
            get {
                return ResourceManager.GetString("donatemethoddesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Help us do better 的本地化字符串。
        /// </summary>
        public static string donatetext1 {
            get {
                return ResourceManager.GetString("donatetext1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似           and keep FREE! 的本地化字符串。
        /// </summary>
        public static string donatetext2 {
            get {
                return ResourceManager.GetString("donatetext2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recover 的本地化字符串。
        /// </summary>
        public static string dorecover {
            get {
                return ResourceManager.GetString("dorecover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download completed! Decompressing. 的本地化字符串。
        /// </summary>
        public static string downloaded {
            get {
                return ResourceManager.GetString("downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string errormessage {
            get {
                return ResourceManager.GetString("errormessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        public static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Would you like to exit ? 的本地化字符串。
        /// </summary>
        public static string exit_cf_mesbox {
            get {
                return ResourceManager.GetString("exit_cf_mesbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Press back again to exit 的本地化字符串。
        /// </summary>
        public static string exitcomfirm {
            get {
                return ResourceManager.GetString("exitcomfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit directly 的本地化字符串。
        /// </summary>
        public static string exitconfirm_0 {
            get {
                return ResourceManager.GetString("exitconfirm_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Press back button for two times 的本地化字符串。
        /// </summary>
        public static string exitconfirm_1 {
            get {
                return ResourceManager.GetString("exitconfirm_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message box confirm 的本地化字符串。
        /// </summary>
        public static string exitconfirm_2 {
            get {
                return ResourceManager.GetString("exitconfirm_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select a way for exit confirm : 的本地化字符串。
        /// </summary>
        public static string exitconfirm_choose {
            get {
                return ResourceManager.GetString("exitconfirm_choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Script engine exited with error code : 的本地化字符串。
        /// </summary>
        public static string exitwitherror {
            get {
                return ResourceManager.GetString("exitwitherror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extract and Import 的本地化字符串。
        /// </summary>
        public static string extandimp {
            get {
                return ResourceManager.GetString("extandimp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 External Storage has been enabled. Please connect your phone to PC and set up a folder named &quot;ADV&quot; in the SD card root and put the game folders into this directory. Then please check this checkbox. NOTICE: because of the API limit of WP8, you must use the fully packaged scripts and games. Currently this feature is not enabled to public and these settings are only for feature preview. 的本地化字符串。
        /// </summary>
        public static string extenabled {
            get {
                return ResourceManager.GetString("extenabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use system player to play video 的本地化字符串。
        /// </summary>
        public static string extVideo {
            get {
                return ResourceManager.GetString("extVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sorry, We met some problems and UVE has to be closed.
        ///Error Description : 的本地化字符串。
        /// </summary>
        public static string fc_text_1 {
            get {
                return ResourceManager.GetString("fc_text_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///If you want to help us solve this bug ,please capture this screen and contact us in the following way:
        ///Email: uve@ligstd.com 的本地化字符串。
        /// </summary>
        public static string fc_text_2 {
            get {
                return ResourceManager.GetString("fc_text_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File 的本地化字符串。
        /// </summary>
        public static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Management 的本地化字符串。
        /// </summary>
        public static string fileclear {
            get {
                return ResourceManager.GetString("fileclear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This application is developed by Light Studio.
        ///Please read our terms of use in the &quot;About&quot; page before using the application. 的本地化字符串。
        /// </summary>
        public static string firstUse {
            get {
                return ResourceManager.GetString("firstUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Float 的本地化字符串。
        /// </summary>
        public static string flo {
            get {
                return ResourceManager.GetString("flo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Float score: 的本地化字符串。
        /// </summary>
        public static string floatscore {
            get {
                return ResourceManager.GetString("floatscore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Folder 的本地化字符串。
        /// </summary>
        public static string folder {
            get {
                return ResourceManager.GetString("folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 force full screen 的本地化字符串。
        /// </summary>
        public static string forcefull {
            get {
                return ResourceManager.GetString("forcefull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Friends 的本地化字符串。
        /// </summary>
        public static string friends {
            get {
                return ResourceManager.GetString("friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Company: 的本地化字符串。
        /// </summary>
        public static string GameCompany {
            get {
                return ResourceManager.GetString("GameCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game Folder 的本地化字符串。
        /// </summary>
        public static string gamefolder {
            get {
                return ResourceManager.GetString("gamefolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Games 的本地化字符串。
        /// </summary>
        public static string GameList {
            get {
                return ResourceManager.GetString("GameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name: 的本地化字符串。
        /// </summary>
        public static string GameName {
            get {
                return ResourceManager.GetString("GameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Author: 的本地化字符串。
        /// </summary>
        public static string GamePort {
            get {
                return ResourceManager.GetString("GamePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game save file 的本地化字符串。
        /// </summary>
        public static string gamesavefile {
            get {
                return ResourceManager.GetString("gamesavefile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size: 的本地化字符串。
        /// </summary>
        public static string GameSize {
            get {
                return ResourceManager.GetString("GameSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General 的本地化字符串。
        /// </summary>
        public static string general {
            get {
                return ResourceManager.GetString("general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Visit UVEngine in store 的本地化字符串。
        /// </summary>
        public static string gotostore {
            get {
                return ResourceManager.GetString("gotostore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide debug information 的本地化字符串。
        /// </summary>
        public static string hidedebug {
            get {
                return ResourceManager.GetString("hidedebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uncheck this and you will see all performance information on the screen including fps count, RAM usage and etc. 的本地化字符串。
        /// </summary>
        public static string hidedebug_description {
            get {
                return ResourceManager.GetString("hidedebug_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please set up a new folder in your phone&apos;s Pictures folder called &quot;UVE&quot; and copy all the png file you want to import to the 的本地化字符串。
        /// </summary>
        public static string imp_t_1 {
            get {
                return ResourceManager.GetString("imp_t_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 of it. Those pictures will appear here and you can import them in one click. 的本地化字符串。
        /// </summary>
        public static string imp_t_2 {
            get {
                return ResourceManager.GetString("imp_t_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sometimes you may have to restart the phone to see them appear here. Free space : 的本地化字符串。
        /// </summary>
        public static string imp_t_3 {
            get {
                return ResourceManager.GetString("imp_t_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Here are the files : 的本地化字符串。
        /// </summary>
        public static string imp_t_4 {
            get {
                return ResourceManager.GetString("imp_t_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import All 的本地化字符串。
        /// </summary>
        public static string impall {
            get {
                return ResourceManager.GetString("impall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import 的本地化字符串。
        /// </summary>
        public static string import {
            get {
                return ResourceManager.GetString("import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Important file 的本地化字符串。
        /// </summary>
        public static string importantfile {
            get {
                return ResourceManager.GetString("importantfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use in app purchase($0.99 every time) 的本地化字符串。
        /// </summary>
        public static string inapppurchase {
            get {
                return ResourceManager.GetString("inapppurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Integer 的本地化字符串。
        /// </summary>
        public static string integer {
            get {
                return ResourceManager.GetString("integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Integer score: 的本地化字符串。
        /// </summary>
        public static string integerscore {
            get {
                return ResourceManager.GetString("integerscore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UVEngine contains ONScripter-jh Compatible Layer, with which you can use most of the ONScripter features. Please visit the following sites to get specific information : https://bitbucket.org/jh10001/onscripter-jh 的本地化字符串。
        /// </summary>
        public static string Intro {
            get {
                return ResourceManager.GetString("Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Latest News 的本地化字符串。
        /// </summary>
        public static string latest {
            get {
                return ResourceManager.GetString("latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Launching feature 的本地化字符串。
        /// </summary>
        public static string launch {
            get {
                return ResourceManager.GetString("launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error occured while loading the list : 的本地化字符串。
        /// </summary>
        public static string listerror {
            get {
                return ResourceManager.GetString("listerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Write log file 的本地化字符串。
        /// </summary>
        public static string logOutput {
            get {
                return ResourceManager.GetString("logOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximum RAM that this app used : 的本地化字符串。
        /// </summary>
        public static string maximumram {
            get {
                return ResourceManager.GetString("maximumram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message 的本地化字符串。
        /// </summary>
        public static string message {
            get {
                return ResourceManager.GetString("message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You must sign in first . 的本地化字符串。
        /// </summary>
        public static string mustsignin {
            get {
                return ResourceManager.GetString("mustsignin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is an error with the Internet connection.
        ///OpenXLive is an online feature. You must connect to the Internet to use it. 的本地化字符串。
        /// </summary>
        public static string networkerror {
            get {
                return ResourceManager.GetString("networkerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Don&apos;t show again (Donate users only) 的本地化字符串。
        /// </summary>
        public static string nomoredisplay {
            get {
                return ResourceManager.GetString("nomoredisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No pictures found in UVE album 的本地化字符串。
        /// </summary>
        public static string nopicfound {
            get {
                return ResourceManager.GetString("nopicfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 normal (4:3) 的本地化字符串。
        /// </summary>
        public static string normal {
            get {
                return ResourceManager.GetString("normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your phone does not support SD card or you haven&apos;t inserted one. 的本地化字符串。
        /// </summary>
        public static string nosd {
            get {
                return ResourceManager.GetString("nosd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your disk space is not enough for testing disk performance. Will skip this step. 的本地化字符串。
        /// </summary>
        public static string notenoughspacefortest {
            get {
                return ResourceManager.GetString("notenoughspacefortest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The copy of the application you installed is NOT purchased and installed from Windows Phone Store.
        ///We need your support to make the software better.
        ///Do you want to go to Windows Phone Store to see this application? 的本地化字符串。
        /// </summary>
        public static string notfrommarket {
            get {
                return ResourceManager.GetString("notfrommarket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 nothing 的本地化字符串。
        /// </summary>
        public static string nothing {
            get {
                return ResourceManager.GetString("nothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 notify 的本地化字符串。
        /// </summary>
        public static string notify {
            get {
                return ResourceManager.GetString("notify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current: 的本地化字符串。
        /// </summary>
        public static string now {
            get {
                return ResourceManager.GetString("now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Okay 的本地化字符串。
        /// </summary>
        public static string okay {
            get {
                return ResourceManager.GetString("okay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Online 的本地化字符串。
        /// </summary>
        public static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Online Players 的本地化字符串。
        /// </summary>
        public static string onlinePlayer {
            get {
                return ResourceManager.GetString("onlinePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Opening File 的本地化字符串。
        /// </summary>
        public static string openfile {
            get {
                return ResourceManager.GetString("openfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OpenXLive Game Center 的本地化字符串。
        /// </summary>
        public static string openxlive {
            get {
                return ResourceManager.GetString("openxlive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OpenXLive config file 的本地化字符串。
        /// </summary>
        public static string openxliveconfig {
            get {
                return ResourceManager.GetString("openxliveconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OpenXLive service is not running. Do you have an internet connection ? 的本地化字符串。
        /// </summary>
        public static string openxliveproblem {
            get {
                return ResourceManager.GetString("openxliveproblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other Folder/File 的本地化字符串。
        /// </summary>
        public static string otherfolder {
            get {
                return ResourceManager.GetString("otherfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter your password.
        ///If you type the wrong password, the application will close. 的本地化字符串。
        /// </summary>
        public static string passwdmes {
            get {
                return ResourceManager.GetString("passwdmes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password Required 的本地化字符串。
        /// </summary>
        public static string passwdreq {
            get {
                return ResourceManager.GetString("passwdreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password saved! 的本地化字符串。
        /// </summary>
        public static string passwordsaved {
            get {
                return ResourceManager.GetString("passwordsaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Performance Test 的本地化字符串。
        /// </summary>
        public static string performancetest {
            get {
                return ResourceManager.GetString("performancetest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Performance Test 的本地化字符串。
        /// </summary>
        public static string perftest {
            get {
                return ResourceManager.GetString("perftest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The device is being tested, do you like to exit ? It may have some files remained if you exit now. 的本地化字符串。
        /// </summary>
        public static string perftestexittip {
            get {
                return ResourceManager.GetString("perftestexittip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total score 的本地化字符串。
        /// </summary>
        public static string perftotal {
            get {
                return ResourceManager.GetString("perftotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Phone Storage 的本地化字符串。
        /// </summary>
        public static string phonestorage {
            get {
                return ResourceManager.GetString("phonestorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Picture Cache 的本地化字符串。
        /// </summary>
        public static string piccache {
            get {
                return ResourceManager.GetString("piccache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PIN to start 的本地化字符串。
        /// </summary>
        public static string pintostart {
            get {
                return ResourceManager.GetString("pintostart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Platform Data 的本地化字符串。
        /// </summary>
        public static string platformdata {
            get {
                return ResourceManager.GetString("platformdata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Push service enabled 的本地化字符串。
        /// </summary>
        public static string pushenabled {
            get {
                return ResourceManager.GetString("pushenabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Push notification has been enabled 的本地化字符串。
        /// </summary>
        public static string pushhasstarted {
            get {
                return ResourceManager.GetString("pushhasstarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Push Notifications 的本地化字符串。
        /// </summary>
        public static string pushswitch {
            get {
                return ResourceManager.GetString("pushswitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quick Import 的本地化字符串。
        /// </summary>
        public static string quickImp {
            get {
                return ResourceManager.GetString("quickImp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quick Share 的本地化字符串。
        /// </summary>
        public static string quickshare {
            get {
                return ResourceManager.GetString("quickshare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable this feature and you will be able to share what you are playing with a automatically done screen capture by full pressing the camera button in the application. Remember NOT to share anything illegal or unsuitable to the SNS service you use. 的本地化字符串。
        /// </summary>
        public static string quicksharedesc {
            get {
                return ResourceManager.GetString("quicksharedesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rate for us 的本地化字符串。
        /// </summary>
        public static string rate {
            get {
                return ResourceManager.GetString("rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Read game data from sd card 的本地化字符串。
        /// </summary>
        public static string readfromsd {
            get {
                return ResourceManager.GetString("readfromsd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel ? 的本地化字符串。
        /// </summary>
        public static string really {
            get {
                return ResourceManager.GetString("really", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Removing files now. Will continue removing after you leave this page. 的本地化字符串。
        /// </summary>
        public static string removing {
            get {
                return ResourceManager.GetString("removing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to reserve the save files? 的本地化字符串。
        /// </summary>
        public static string reservesave {
            get {
                return ResourceManager.GetString("reservesave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LeftToRight 的本地化字符串。
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save data restored! 的本地化字符串。
        /// </summary>
        public static string restorecompleted {
            get {
                return ResourceManager.GetString("restorecompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Review this app in store 的本地化字符串。
        /// </summary>
        public static string reviewinstore {
            get {
                return ResourceManager.GetString("reviewinstore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ROOT DIRECTORY 的本地化字符串。
        /// </summary>
        public static string rootdirectory {
            get {
                return ResourceManager.GetString("rootdirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run 的本地化字符串。
        /// </summary>
        public static string run {
            get {
                return ResourceManager.GetString("run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SD Card 的本地化字符串。
        /// </summary>
        public static string sdcard {
            get {
                return ResourceManager.GetString("sdcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 External Storage has been inserted. Would you like to enable External Storage?(Notice : Current version does NOT support games in SD card ) 的本地化字符串。
        /// </summary>
        public static string sdinserted {
            get {
                return ResourceManager.GetString("sdinserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 External Storage is not enabled. Please connect your phone to PC and set up a folder named &quot;ADV&quot; in the SD card root and put the game folders into this directory. Then please check this checkbox. NOTICE: because of the API limit of WP8, you must use the fully packaged scripts and games. Currently this feature is not enabled to public and these settings are only for feature preview. 的本地化字符串。
        /// </summary>
        public static string sdnotenabled {
            get {
                return ResourceManager.GetString("sdnotenabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select 的本地化字符串。
        /// </summary>
        public static string selectandimp {
            get {
                return ResourceManager.GetString("selectandimp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Import 的本地化字符串。
        /// </summary>
        public static string selectImp {
            get {
                return ResourceManager.GetString("selectImp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select your save file 的本地化字符串。
        /// </summary>
        public static string selectyoursave {
            get {
                return ResourceManager.GetString("selectyoursave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Application bar translucent 的本地化字符串。
        /// </summary>
        public static string setopacity {
            get {
                return ResourceManager.GetString("setopacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 require a password to use the app 的本地化字符串。
        /// </summary>
        public static string setpasswdreq {
            get {
                return ResourceManager.GetString("setpasswdreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shared Folder 的本地化字符串。
        /// </summary>
        public static string shared {
            get {
                return ResourceManager.GetString("shared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To store tiles&apos; pictures or etc. 的本地化字符串。
        /// </summary>
        public static string sharedusage {
            get {
                return ResourceManager.GetString("sharedusage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 show donate page 的本地化字符串。
        /// </summary>
        public static string showdonate {
            get {
                return ResourceManager.GetString("showdonate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Single : 的本地化字符串。
        /// </summary>
        public static string singleprogress {
            get {
                return ResourceManager.GetString("singleprogress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Available disk space not enough. 的本地化字符串。
        /// </summary>
        public static string spacenotenough {
            get {
                return ResourceManager.GetString("spacenotenough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Begin 的本地化字符串。
        /// </summary>
        public static string starttest {
            get {
                return ResourceManager.GetString("starttest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop 的本地化字符串。
        /// </summary>
        public static string stoptest {
            get {
                return ResourceManager.GetString("stoptest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Storage 的本地化字符串。
        /// </summary>
        public static string storage {
            get {
                return ResourceManager.GetString("storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Free space : 的本地化字符串。
        /// </summary>
        public static string storageleft {
            get {
                return ResourceManager.GetString("storageleft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CLR 的本地化字符串。
        /// </summary>
        public static string str {
            get {
                return ResourceManager.GetString("str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CLR score : 的本地化字符串。
        /// </summary>
        public static string strcutscore {
            get {
                return ResourceManager.GetString("strcutscore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System Folder 的本地化字符串。
        /// </summary>
        public static string systemfolder {
            get {
                return ResourceManager.GetString("systemfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test 的本地化字符串。
        /// </summary>
        public static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test completed 的本地化字符串。
        /// </summary>
        public static string testfinished {
            get {
                return ResourceManager.GetString("testfinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Thank you for your support. We will receive it soon. 的本地化字符串。
        /// </summary>
        public static string thanks {
            get {
                return ResourceManager.GetString("thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Thanks for your donation 的本地化字符串。
        /// </summary>
        public static string thanksdonation {
            get {
                return ResourceManager.GetString("thanksdonation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You seem to have already pinned the game to start.
        ///Here comes the error message: 的本地化字符串。
        /// </summary>
        public static string tileerror {
            get {
                return ResourceManager.GetString("tileerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Notice 的本地化字符串。
        /// </summary>
        public static string tip {
            get {
                return ResourceManager.GetString("tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total : 的本地化字符串。
        /// </summary>
        public static string totalprog {
            get {
                return ResourceManager.GetString("totalprog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total : 的本地化字符串。
        /// </summary>
        public static string totalprogress {
            get {
                return ResourceManager.GetString("totalprogress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RAM size of this phone : 的本地化字符串。
        /// </summary>
        public static string totalram {
            get {
                return ResourceManager.GetString("totalram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Traditional import method 的本地化字符串。
        /// </summary>
        public static string traditionalimport {
            get {
                return ResourceManager.GetString("traditionalimport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to have a free trail first? 的本地化字符串。
        /// </summary>
        public static string trailversion {
            get {
                return ResourceManager.GetString("trailversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disk space used by UVE : 的本地化字符串。
        /// </summary>
        public static string usedstorage {
            get {
                return ResourceManager.GetString("usedstorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Video playback error : 的本地化字符串。
        /// </summary>
        public static string videoplaybackerror {
            get {
                return ResourceManager.GetString("videoplaybackerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 display properties 的本地化字符串。
        /// </summary>
        public static string vsetting {
            get {
                return ResourceManager.GetString("vsetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WARNING 的本地化字符串。
        /// </summary>
        public static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 wide screen (16:9) 的本地化字符串。
        /// </summary>
        public static string wide {
            get {
                return ResourceManager.GetString("wide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Application will remove all the data and then exit automatically. it may take some time. 的本地化字符串。
        /// </summary>
        public static string willremove {
            get {
                return ResourceManager.GetString("willremove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UVE will close to apply these changes. Please restart UVE to complete the process. 的本地化字符串。
        /// </summary>
        public static string willrestart {
            get {
                return ResourceManager.GetString("willrestart", resourceCulture);
            }
        }
    }
}
